{
 "title": "Mini URLs usage details",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Mini URLs created",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"builderAPI\"} |= `mini url sent successfully`"
    }
   ]
  },
  {
   "title": "Mini URLs sent by API",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=\"service\"} |= `mini url sent successfully`"
    }
   ]
  },
  {
   "title": "Mini URLs served",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container_name=\"service\"} |= `mini url served successfully`"
    }
   ]
  },
  {
   "title": "Mini URLs retrieved from database",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{container_name=\"service\"} |= `does not exist on cache` | regexp `^(?P<value>[a-zA-Z0-9]+)`"
    }
   ]
  }
 ]
}